// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnlje27l4fBUdhTKw9D2MN68aSyh3LjKs',
    appId: '1:223986387958:web:a40e07373f4d38e65515d7',
    messagingSenderId: '223986387958',
    projectId: 'zimtap',
    authDomain: 'zimtap.firebaseapp.com',
    databaseURL: 'https://zimtap-default-rtdb.firebaseio.com',
    storageBucket: 'zimtap.firebasestorage.app',
    measurementId: 'G-JP5PJP2P8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5-sBS39H_OQwmKH3rfPmSaxL2PDxmWuA',
    appId: '1:223986387958:android:05d4934ef34ae9e25515d7',
    messagingSenderId: '223986387958',
    projectId: 'zimtap',
    databaseURL: 'https://zimtap-default-rtdb.firebaseio.com',
    storageBucket: 'zimtap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv34pRrL6NqrzhJe7WjErZaqRfictOMso',
    appId: '1:223986387958:ios:ba32890ed4f91e385515d7',
    messagingSenderId: '223986387958',
    projectId: 'zimtap',
    databaseURL: 'https://zimtap-default-rtdb.firebaseio.com',
    storageBucket: 'zimtap.firebasestorage.app',
    androidClientId: '223986387958-gkeks7pq2s5ntd9ro044afqlocvt8vkq.apps.googleusercontent.com',
    iosClientId: '223986387958-nf498hrm2mld30pf2ahpm7rs4qudsucj.apps.googleusercontent.com',
    iosBundleId: 'com.mrbeewar.zimtap',
  );

}